### ISSUE TITLE
Incorrect Parsing of `t.Number()` and `t.Numeric()` Reference Model in Swagger Documentation

### ISSUE THREAD

**Issue by hoywu** [elysiajs/elysia#1013]
### What version of Elysia is running?

1.2.10

### What platform is your computer?

Linux 6.12.9-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Use the `.model` method to create the following two Reference Models:

```ts
import swagger from "@elysiajs/swagger";
import { Elysia, t } from "elysia";

const app = new Elysia()
  .use(swagger())
  .model("number", t.Number())
  .model("numeric", t.Numeric())
  .listen(3000);
```

Then visit `http://localhost:3000/swagger/json`

### What is the expected behavior?

```json5
{
  // ...
  "components": {
    "schemas": {
      "number": {
        "type": "number"
      },
      "numeric": {
        "anyOf": [
          {
            "format": "numeric",
            "default": 0,
            "type": "string"
          },
          {
            "type": "number"
          }
        ]
      }
    }
  }
}
```

### What do you see instead?

The `number` model is parsed into a structure similar to numeric, and `numeric` get some strange nesting

```json5
{
  // ...
  "components": {
    "schemas": {
      "number": {
        "type": "number",
        "anyOf": [
          {
            "type": "string",
            "format": "numeric",
            "default": 0
          },
          {
            "type": "number"
          }
        ]
      },
      "numeric": {
        "anyOf": [
          {
            "format": "numeric",
            "default": 0,
            "type": "string"
          },
          {
            "type": "number",
            "anyOf": [
              {
                "type": "string",
                "format": "numeric",
                "default": 0
              },
              {
                "type": "number"
              }
            ]
          }
        ]
      }
    }
  }
}
```

### Additional information

After bisecting, the commit https://github.com/elysiajs/elysia/commit/57b24c1cf531844607fd0e46f7b6b7a920f117f6 appeared to be the reason.

`elysia@1.2.6` does not have this issue.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by hoywu** [comment]
Commit 57b24c1 seems to be related to all of the following issues:

#1015 #1007 #1003

**Comment by Mudbill** [comment]
+1
Also encountered similar issues. After upgrading I had a whole tower of nested type definitions like the above (something like 20 levels deep in my existing models).

**Comment by Necrelox** [comment]
Hello, I'm having the same problem. Has there been any feedback on this or even a workaround?

**Comment by hoywu** [comment]
Unfortunately, it seems that the maintainer is currently on vacation. For now, I've temporarily downgraded to `elysia@1.2.6`.

**Comment by recanman** [comment]
As well as for `t.Date`:
![Image](https://github.com/user-attachments/assets/7e026905-688e-4bf3-8411-2c8ce8697ebd)

**Comment by Necrelox** [comment]
Hello, is there any news on this subject?

**Comment by hoywu** [comment]
@Necrelox  this issue still exists in `1.2.25` :)

**Comment by Necrelox** [comment]
This is super important because it has a big impact not only on the documentation, but also on the generation of Scalar UI with large spec

**Comment by recanman** [comment]
Last Elysia-related commit by SaltyAom was two weeks ago...

**Comment by Necrelox** [comment]
@recanman We can't blame him for working on other things, or for taking a break, but it would take several maintainers to develop Elysia, because it's a great project that deserves to be followed.

**Comment by hoywu** [comment]
Hey guys, I noticed this issue seems to have been fixed in the `redhood` branch (with c137799), and it should be included in the upcoming `1.3.0` release!

**Comment by Necrelox** [comment]
@hoywu I can't wait for 1.3.0!  Thank you

**Comment by Necrelox** [comment]
after trying elysia@experimental, it's perfect

**Comment by Galleria** [comment]
This issue will be fixed in version 1.3.0, right?

**Comment by Necrelox** [comment]
@Galleria yes !

**Comment by recanman** [comment]
Tried 1.3.1 and the issue was fixed. @hoywu, I recommend you close the issue.

**Comment by hoywu** [comment]
@recanman Thanks for your reminder. I can confirm that the issue is now fixed, closing this 👍

**Comment by emirefek** [comment]
problem still exists on Date type for me on latest version 1.3.1


```
 createdAt: 
      t.Date({
        title: "User Created At",
        description: "The date and time when the user was created",
        examples: ["2023-10-01T12:00:00Z"],
      }),
```

```
"createdAt": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "Date"
                  },
                  {
                    "format": "date-time",
                    "type": "string"
                  },
                  {
                    "format": "date",
                    "type": "string"
                  },
                  {
                    "type": "number"
                  }
                ],
                "title": "User Created At",
                "description": "The date and time when the user was created",
                "examples": [
                  "2023-10-01T12:00:00Z"
                ],
                "type": "Date"
              },
              {
                "format": "date-time",
                "type": "string"
              },
              {
                "format": "date",
                "type": "string"
              },
              {
                "type": "number"
              }
            ],
            "title": "User Created At",
            "description": "The date and time when the user was created",
            "examples": [
              "2023-10-01T12:00:00Z"
            ]
          },
```
