### ISSUE TITLE
body type is always unknown despite validation

### ISSUE THREAD

**Issue by JohnRoseDev** [elysiajs/elysia#1115]
### What version of Elysia is running?

1.2.25

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Define a route with a body validation config:

```
export const app = new Elysia()
  .post('/do_something', async ({ body }) => {

  }, {
    body: t.Object({
      foo: t.Integer(),
      bar: t.Integer(),
    }),
  })
```

### What is the expected behavior?

The body object from the context parameter should be typed as `{ foo: number, bar: number }`.

### What do you see instead?

The body object from the context parameter is typed as `unknown`.

### Additional information

This started happening some months ago and I was under the impression that eventually, upgrading Elysia each time there's a new version would fix this but it's still happening. I assume something in my tsconfig might be off but I've been using this same tsconfig since the beginning of my Elysia project and this problem was not there initially.

bun version:
1.2.4

"bun-types": "1.2.4"

tsconfig:

```
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "preserveSymlinks": true,
    "strictNullChecks": true,
    "types": ["bun-types"],
  }
}
```

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by hisamafahri** [comment]
Is this also happening when you create a new elysia app (`bun create elysia app`) too?

I cannot reproduce your issue sadly.

---

And juuuust wanna make sure (I assume you've done it correctly), you import the `t` from elysia, right? 😅
```
import Elysia, { t } from "elysia";
```

**Comment by fearandesire** [comment]
I'm suddenly having the same issue as well, when I wasn't within the past few days. Not sure what's changed or what I did, unfortunately.

**Comment by fearandesire** [comment]
> [@JohnRoseDev](https://github.com/JohnRoseDev?rgh-link-date=2025-03-13T07%3A22%3A52.000Z) In my project I used some other of our modules which also uses elysia. So I've run into issues where these dependencies to elysia weren't the same. The time I replied there was also a change for the patch version of typebox (seen in bun.lock; not a direct dependency of our project). But I still don't know which fixed it in the end.
> 
> My steps were:
> 
>     * removing node_modules and bun.lock
> 
>     * starting without elysia and adding dependencies one by one to find the "faulty" one 
>       It seemed like the "right order" solved it here, a bit weird.
> 
> 
> I've also searched for other issues during that day and stumbled upon [#777 ](https://github.com/elysiajs/elysia/issues/777) . But I've seen that you already use this setting.
> 
> Btw I use TS 5.8.2 and the generated tsconfig of bun.


I've tried what you suggested and in other issues and haven't been able to fix it. It's really weird.

To list what I've tried:

- removed `bun.lock`, `node_modules`
 - reinstalled with `bun i`
- `bun pm cache clean`
- tried different IDEs
- various typescript versions:
	- 5.8
	- 5.9.0 (via @next)
	- 5.5.3
- downgraded to Elysia prior version
- tried removing extreneous deps, building with tsc per-dep i installed, but this failed as long as elysia was installed
- override typebox to specific version
- tsconfig with different setups - from example repos, what others listed in other issues, etc
- upgraded bun to latest version
- verified I'm importing as `import Elysia, { t } from 'elysia'`
- even removed typescript globally, reinstalled

I can't for the life of me figure out why this doesn't work suddenly.
I'm new to Elysia and it's just a bit disappointing this suddenly happened, as I've enjoyed the experience so far.

And for more context, my IDE does type the body properly just fine on-hover. I can see what I've defined as the schemas, but `tsc` just won't build them.

**Comment by fearandesire** [comment]
I've fixed it for myself, and I have no idea how 😅

**Comment by Xu-pixel** [comment]
I encountered the same problem, and I solved it by adding "strict": true in the compilerOptions of tsconfig.

**Comment by ratthapolsk** [comment]
# Solution: Fixing "Unknown" Parameter with Model Validation Issue in Elysia

After some investigation and a workaround, I was able to resolve this issue.

## Problem: "Unknown" Parameter Despite Defining the Model in Route

While working in VS Code, I encountered an issue where the route parameter was showing as `unknown`, even though I had properly declared the model.

### VS Code Editor:
![Image](https://github.com/user-attachments/assets/f6f34cc2-8c66-4e56-ad22-8e242df227da)

No matter what I tried, I couldn’t get it to recognize the correct type. However, when I switched to the latest version of Cursor Editor, I found that it correctly inferred the type.

### Cursor Editor:
![Image](https://github.com/user-attachments/assets/1e5cee42-8a8e-47de-bb9f-be628d678714)

## Root Cause: Outdated VS Code and TypeScript Version

After further analysis, I checked the versions of both VS Code and the built-in TypeScript version that ships with it. I realized that my VS Code version was outdated:

```
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.26100
```

Since I was using Windows, I updated VS Code using the following command:

`winget upgrade --id Microsoft.VisualStudioCode`

After updating, I verified the installed TypeScript version within VS Code:

- Press Ctrl + Shift + P

- Search for "Select TypeScript Version"

### Updated TypeScript Version:

![Image](https://github.com/user-attachments/assets/57d50156-7ec6-43ae-b842-2491759867c3)

With the latest VS Code and TypeScript, I checked my index.ts file again—and finally, the parameter types were correctly inferred! 🎉🎉

### Fixed Type Definition in index.ts:

![Image](https://github.com/user-attachments/assets/57d8ac16-2818-4a59-8845-c1eb9b9ed312)

## Conclusion
If you're facing the same issue, try updating your VS Code and TypeScript version. That should resolve the problem!

Good luck! 😁

**Comment by nephix** [comment]
I got the same issue when just running `tsc --noEmit` in console after upgrading typescript to 

```
"typescript": "~5.8.3"
```

`tsc --noEmit`:
```
│ src/setup/http.ts(45,29): error TS7031: Binding element 'set' implicitly has an 'any' type.
│ src/setup/http.ts(50,30): error TS7031: Binding element 'email' implicitly has an 'any' type.
│ src/setup/http.ts(50,37): error TS7031: Binding element 'password' implicitly has an 'any' type.
│ src/setup/http.ts(50,59): error TS7031: Binding element 'rt' implicitly has an 'any' type.
│ src/setup/http.ts(75,26): error TS7031: Binding element 'rt' implicitly has an 'any' type.
│ src/setup/http.ts(75,40): error TS7031: Binding element 'email' implicitly has an 'any' type.
│ src/setup/http.ts(75,47): error TS7031: Binding element 'password' implicitly has an 'any' type.
│ src/setup/http.ts(75,59): error TS7031: Binding element 'error' implicitly has an 'any' type.
│ src/setup/http.ts(90,45): error TS7031: Binding element 'rt' implicitly has an 'any' type.
│ src/setup/http.ts(97,26): error TS7031: Binding element 'rt' implicitly has an 'any' type.
│ src/setup/http.ts(97,41): error TS7031: Binding element 'token' implicitly has an 'any' type.
│ src/setup/http.ts(119,25): error TS7031: Binding element 'code' implicitly has an 'any' type.
│ src/setup/http.ts(119,31): error TS7031: Binding element 'idToken' implicitly has an 'any' type.
│ src/setup/http.ts(119,52): error TS7031: Binding element 'rt' implicitly has an 'any' type.
```

eg here:

```ts
.post(
    '/auth/sign-up',
    async ({ body: { email, password }, cookie: { rt } }) => {
        // ...
    },
    {
        body: t.Object({
            email: t.String(),
            password: t.String(),
        }),
        cookie: t.Cookie({
            rt: t.Optional(t.String()),
        }),
    },
)
```

deps:

```
"@types/bun": "1.2.12",
"elysia": "^1.1.6",
```

**Comment by ppenter** [comment]
I fixed by strict: true.

**Comment by incpo** [comment]
That is also caused by `"strictNullChecks": false` in `tsconfig.json`, so make sure it is set to true.

**Comment by mmatila** [comment]
Upgrading to latest Typescript version which in my case happened to be `typescript@5.8.3` fixed it for me!

**Comment by playgod123456-art** [comment]
In my case, the issue was resolved by updating:

```json
"overrides": {
  "@sinclair/typebox": "0.32.4"
}
```

to

```json
"@sinclair/typebox": "^0.34.0"
```

After upgrading to `0.34.0`, everything started working again.

**Comment by pranavp10** [comment]
In my case, the issue was resolved by updating:

```json
"overrides": {
  "@sinclair/typebox": "0.32.4"
}
```

to

```json
"@sinclair/typebox": "^0.34.0"
```

After upgrading to `0.34.0`, everything started working again.

**Comment by joaottc** [comment]
Still having this issue with typebox or zod, "elysia": "1.4.18", typescript 5.9.3 and latest version if vscode as of today

**Comment by KevinBrogan** [comment]
> I encountered the same problem, and I solved it by adding "strict": true in the compilerOptions of tsconfig.

This fixed it for me after hours of grief. I can toggle strict on and off and watch the problem come back and disappear. *rage and tears*
