### ISSUE TITLE
Type error in group decorator

### ISSUE THREAD

**Issue by makaias** [elysiajs/elysia#130]
Whenever I try to create a group which uses decorator for database access the following problem happens:
The group is working as intended as long as I don't need to access the database.
When it comes to the database access, the instance (in this example the BooksDatabase instance) produces the following error:
`TypeError: db.getBooks is not a function. (In 'db.getBooks()', 'db.getBooks' is undefined)`

The error only happens in groups, when I try the same with a db decorator on the main Elysia instance it works without any issues.
Is there any workaround for this, or any step I missed?
Thanks for the help! :)

Demo code for the issue:
```
import { swagger } from "@elysiajs/swagger";
import Database from "bun:sqlite";
import { Elysia, t } from "elysia";

interface Book {
  id?: number;
  name: string;
  author: string;
}

class BooksDatabase {
  private db: Database;

  constructor() {
    this.db = new Database("books.db");
    this.init()
      .then(() => console.log("Database initialized"))
      .catch(console.error);
  }

  async getBooks() {
    return this.db.query("SELECT * FROM books").all();
  }

  async init() {
    return this.db.run(
      "CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, author TEXT)"
    );
  }
}

const bookService = new Elysia({ prefix: "/books" })
  .model({
    book: t.Object({
      name: t.String(),
      author: t.String(),
    }),
  })
  .decorate("db", new BooksDatabase())
  .get("/", async ({ db }) => await getAllBooks(db));

const getAllBooks = async (db: BooksDatabase) => {
  try {
    const books = await db.getBooks();
    return { success: true, books };
  } catch (e) {
    console.log(e);
    return { success: false };
  }
};

const app = new Elysia()
  .model({
    book: t.Object({
      name: t.String(),
      author: t.String(),
    }),
  })
  .use(swagger())
  .group("/v1", (app) => app.use(bookService))
  .listen(8080);
```

package.json:
```{
  "name": "elysiaTest",
  "version": "1.0.50",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "bun run --watch src/index.ts"
  },
  "dependencies": {
    "@elysiajs/cookie": "^0.6.1",
    "@elysiajs/cors": "^0.6.0",
    "@elysiajs/swagger": "^0.6.2",
    "elysia": "latest"
  },
  "devDependencies": {
    "bun-types": "latest"
  },
  "module": "src/index.js"
}```

**Comment by gmenih** [comment]
This is the same issue as #143

**Comment by SaltyAom** [comment]
Should be fixed in https://github.com/elysiajs/elysia/pull/103.

Let me know if the problem stills persists

**Comment by mathipalm** [comment]
Tested with example above on `"elysia": "^0.7.1"` and i still have the same issue @SaltyAom

**Comment by SaltyAom** [comment]
Can't replicate with above code on my end, maybe Bun doesn't update the cache?

This is specifically resolved in `0.7.1`, can you try running:
```bash
```

**Comment by mathipalm** [comment]
@SaltyAom my bad, slight confusion on my end. The above example working but i notice the issue persists when adding the decorator outside the group. 

this works:
```
const bookService = new Elysia({ prefix: '/books' })
  .decorate('db', new BooksDatabase())
  .get('/', async ({ db }) => await getAllBooks(db))
const app = new Elysia()
  .group('/v1', app => app.use(bookService))
  .listen(8080)
  ```
  
this don't:
```
const bookService = new Elysia({ prefix: '/books' })
  .get('/', async ({ db }) => await getAllBooks(db))
const app = new Elysia()
  .decorate('db', new BooksDatabase())
  .group('/v1', app => app.use(bookService))
  .listen(8080)
  ```
  
 But maybe thats not suppose to work in the first place? Or are we suppose to add the decorator to every group? If created seperatly?

**Comment by makaias** [comment]
@SaltyAom it works now, thank you!
