### ISSUE TITLE
Cannot use `Context.set` outside of the request handler

### ISSUE THREAD

**Issue by pilcrowOnPaper** [elysiajs/elysia#136]
```ts
const setCookie = (context: Context) => {
  context.set.headers["Set-Cookie"] = "foo=bar;path=/";
};

const app = new Elysia()
  .get("/", (context) => {
    setCookie(context as any);
    return "Hello world";
  })
  .listen(3000);
```

I'd expect the `Set-Cookie`response header to be set but it's not. Interestingly, the header gets applied if I add `context.set` to the request handler. Same issue can be seen for `Context.set.status`. 

## Reproduction 

https://github.com/pilcrowOnPaper/elysia-set-header-repro

**Comment by SaltyAom** [comment]
Should be fixed in 0.7 #103.

However, I don't recommend passing an entire context, since Elysia will lose the ability to analyze property leading to slightly worse performance statically.

**Comment by pilcrowOnPaper** [comment]
Thanks, tried the reproduction with 0.7.1 and it seems to be fixed :D

**Comment by pilcrowOnPaper** [comment]
Looks like this was only fixed for local files (like the repro), and it's still an issue if you try to use a node_modules that set cookies/headers
