### ISSUE TITLE
[OPENAPI / Elysia] No parameters in operation object + broken response when setting params in hook object

### ISSUE THREAD

**Issue by Necrelox** [elysiajs/elysia#1399]
### What version of Elysia is running?

elysia@1.3.21

### What platform is your computer?

Linux 6.16.6-3-cachyos x86_64 unknown

### What environment are you using

1.2.21

### Are you using dynamic mode?

no

### What steps can reproduce the bug?

```ts
new Elysia()
	.use(openapi())
	.model({
		idParam: t.Object({
			id: t.Union([
				t.String({ format: 'uuid' }),
				t.Number({ minimum: 1, maximum: Number.MAX_SAFE_INTEGER })
			])
		}),
		response200: t.Object({
			message: t.String(),
			content: t.Array(t.Object({
				id: t.Union([t.String(), t.Number()])
			}))
		})
	})
	.get('/:id', ({ params: { id } }) => ({
		message: 'ok',
		content: [{ id }]
	}), {
		params: 'idParam',
		response: 'response200'
	})
	.listen(3000);
```

### What is the expected behavior?

https://spec.openapis.org/oas/latest.html#operation-object

- Parameters should appear in the operation object.
- When I set params together with responses in the hook parameters for a route, the schemas should work correctly.

Example of expected response:
```ts
{
  "message": "ok",
  "content": [
    {
      "id": "22"
    }
  ]
}
```

### What do you see instead?

- In the generated documentation, no parameters are shown.
- More importantly, when params are set together with responses in the hook parameters, the returned response is incorrectly parsed.

Example of actual response:
```ts
{
  "message": "ok",
  "content": "[\"{\\\"id\\\":22}\"]"
}
```

**Comment by SaltyAom** [comment]
Fixed by [f620038](https://github.com/elysiajs/elysia/pull/1403/commits/f6200388471749b52adf7b18f7cb07d267b9f661) in #1403 

To test it out locally, install the patch package
```bash
bun add https://pkg.pr.new/elysiajs/elysia@1403
```

**Comment by Necrelox** [comment]
Thank you very much! I'll test it out today!

**Comment by Necrelox** [comment]
Hello!
The response is fine now ! but the openapi is still broken. When I put params in validation, it still doesn't appear in scalar

<img width="1724" height="620" alt="Image" src="https://github.com/user-attachments/assets/2e22e81e-b0a3-4eb8-8d0a-e1f33c06ee7c" />

**Comment by SaltyAom** [comment]
Hi, sorry for the late response. Does this problem this persists?

**Comment by Necrelox** [comment]
> Hi, sorry for the late response. Does this problem this persists?

Hello, don't worry, it's perfect now. Thank you so much ❤️!
