### ISSUE TITLE
t.Numeric not validating properly

### ISSUE THREAD

**Issue by sheryy** [elysiajs/elysia#210]
```
const users = new Elysia({ prefix: "/users/:userId" })
  .get(
    "/",
    ({ params: { userId } }) => {
      return { userId, timestamp: Date.now() };
    },
    {
      params: t.Object({
        userId: t.Numeric({ minimum: 0 }),
      }),
    }
  )
```

The above mentioned code shall reject inputs like _http://localhost:3000/users/x_ as per the [documentation](https://elysiajs.com/concept/numeric.html) which states that "_If string is not a valid numeric string, it will throw an error in the runtime and prevent and execution inside the handler_".

Also the following input works as well even though **minimum** is set to zero: _http://localhost:3000/users/-1_

I had to revert to the following code for correct behavior:
```
const users = new Elysia({ prefix: "/users/:userId" }).get(
  "/",
  ({ params: { userId } }) => {
    return { userId, timestamp: Date.now() };
  },
  {
    params: t.Object({
      userId: t.Number({ minimum: 0 }),
    }),
    transform({ params }) {
      const userId = +params.userId;
      if (isNaN(userId) === false) {
        params.userId = userId;
      }
    },
  }
);

```

**Comment by SaltyAom** [comment]
Should be fixed in https://github.com/elysiajs/elysia/commit/62cd02a187abb80088c55896d390e2966ab225b4

Let me know if the problem this persists

**Comment by je-bert** [comment]
The problem still persists.

I tried with the following code:
`
import { Elysia, t } from "elysia";

const app = new Elysia()
  .get("/id/:id", ({ params: { id } }) => id, {
    params: t.Object({
      id: t.Numeric({ default: 1, minimum: 1, maximum: 100 }),
    }),
  })
  .get("/", () => "Hello Elysia")
  .listen(3000);
`

**Comment by gabbrieu** [comment]
Any news? Problem still persists today

**Comment by SaltyAom** [comment]
Fix with eabe264, available on 0.7.27.

Feel free to reopen if the issue still persists.
