### ISSUE TITLE
Parameters as last object in the slug causes following "unwanted/unexpected" slugs to be ignored and still used for the intended one

### ISSUE THREAD

**Issue by Northernside** [elysiajs/elysia#23]
I'm sorry lmao, I don't know how to describe it properly (that's why the title might be confusing asf), but:
My code has an `POST` endpoint which listens on `/api/profile/:username`. Previously, there was also an `DELETE` endpoint on `/api/profile/:username/modules`. I've removed that one though, as I've implemented another route for that. There also exists an `DELETE` endpoint for `/api/profile/:username`.
The thing is, when (still) trying to use `DELETE` on `/api/profile/:username/modules`, even though it's not implemented anymore, it'll straight up use `DELETE` on `/api/profile/:username` (but it also remove the `/modules` at the end, so it's really using the supplied username).
I don't think this should happen. It should rather display a 404 because well, `/api/profile/:username/modules` doesn't exist anymore.
How did I find out about this? Maaayyybee.. Just maaayyybe, I've accidently deleted accounts within my project without knowing until now 🥲
If you need PoC code, lmk!

Regards,
~ Northernside

**Comment by xevaly** [comment]
➕ same issue

**Comment by SaltyAom** [comment]
I'm very sorry to hear that.

I have just updated an improved router which should be more stable yesterday [raikiri #2](https://github.com/SaltyAom/raikiri/issues/2), can you try updating to 0.3.0-rc.8 to see if this still happens?

If this still happens, please file an issue at [the router](https://github.com/saltyaom/raikiri)

**Comment by Northernside** [comment]
Will test later, thanks in advance!

**Comment by Northernside** [comment]
Ohh, seems like I forgot this 👀
Anyways, iirc the issue didn't happen anymore, but right now, I'm experiencing a "similar" issue.
For whatever reason, accessing **GET** `/api/search/example/0` calls the **GET** `/api/view/:id` handler. Is there a particular reason?

<img width="719" alt="image" src="https://user-images.githubusercontent.com/60970791/232343805-0ad3ad5c-c5df-4ea4-b18f-7fee4f48e465.png">
<img width="364" alt="image" src="https://user-images.githubusercontent.com/60970791/232343832-cd054d6d-1d40-406a-8098-ec6f758a91eb.png">

**Comment by Northernside** [comment]
Ohh, seems like I fixed it? But it's still strange, because above **GET** `/api/search/example/0` there's another route called **GET** `/register/:email/:password/:username` (params bc I was testing stuff and wanted it to be quick). Now I've moved that one beneath **GET** `/api/view/:id` and everything works properly now, but that seems strange. 👀

**Comment by SaltyAom** [comment]
Seems like a problem with the router re-ordering.
What version of Elysia are you when you have this problem?

**Comment by Northernside** [comment]
Sorry for the late response, I was on a trip the past few days!
Last time I tested it, I've used 0.4.6 and now I've updated all dependencies and it unfortunately still breaks.

**Comment by SaltyAom** [comment]
I got this reported on Discord too, update Elysia to 0.4.9 should fix the problem.

**Comment by Northernside** [comment]
Still not working, I theoretically could add/give you access to my code for you to debug/further look into i. Though I'd do this as a last resort, because the code is somewhat "confidential". I also ran `bun pm cache clear`, deleted `bun.lockb` & `node_modules/` and reran `bun install`.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/60970791/234054616-3383bd18-88be-4b71-b9f5-745b05e6337a.png">

**Comment by SaltyAom** [comment]
This is likely the problem caused by our in-house router, I published a package to fix this on Elysia `^0.4.10` by using your code as the test case, please update to see if this fixes your problem.

In the next version, we are working on migrating to use a more well-known and more stable router.

Let me know if this fix your problem

**Comment by Northernside** [comment]
Don't be sorry! I'm using `/api/_xyz/view/:id` and `/api/xyz/search/:type/:filter/:chunk` at the moment in order to avoid that issue.
`0.4.10` didn't fix it either, but again, don't worry, take you time please :D
If you need my code for testing, let me know! And don't stress yourself with the next release please 🫶

**Comment by SaltyAom** [comment]
Hi, I'm sorry to bother you again but I published an experimental version for using a new router at `^ elysia@0.5.0-exp-230425.1742`, if possible, can I ask you a favor to install this version and see if the problem still persists.

This router will be a default router in 0.5 for stability, please let me know if this fixes your problem.

If so, you can continue to use this version as it's likely stable and doesn't have any difference behavior from 0.4.
