### ISSUE TITLE
Option to return errors as JSON

### ISSUE THREAD

**Issue by hassanshaikley** [elysiajs/elysia#313]
Hey, it would be nice to be able to do that.
I understand the onError callback but that requires a good bit of finessing to convert to JSON.
In particular I am thinking of validator errors.

**Comment by SaltyAom** [comment]
I'm not sure if you mean or:
1. Returning Error from handler as JSON
2. Returning built-in Elysia errors like ValidationError, NotFound as JSON.

Either way, you should be able to use https://elysiajs.com/patterns/error-handling.html#catching-all-error

**Comment by oSethoum** [comment]
what he means is for elysia to automatically send back the validation error as JSON not in plain text
what should I do with this in my client side app? parse it?
![image](https://github.com/elysiajs/elysia/assets/88779394/ae5ac08a-89ad-4812-a6fb-23a03c302fab)

**Comment by hassanshaikley** [comment]
Exactly @oSethoum! 

If not automatically then it should be easier. I suppose I can look into creating a plugin for this?

**Comment by wiredmatt** [comment]
import { Elysia, t } from "elysia";
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const app = new Elysia()
  .post(
    "/sign-up",
    async ({ body }) =>
      db.user.create({
        data: body,
      }),
    {
      body: t.Object({
        username: t.String(),
        password: t.String({
          minLength: 8,
        }),
      }),
      error({ code, error }) {
        switch (code) {
          case "VALIDATION":
            console.log(error.all);

            // Find a specific error name (path is OpenAPI Schema compliance)
            const name = error.all.find((x) => x.path === "/name");

            // If has validation error, then log it
            if (name) console.log(name);

            return error.all;
          default:
            return {
              name: error.name,
              message: error.message,
            };
        }
      },
    }
  )
  .listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
![image](https://github.com/elysiajs/elysia/assets/29718978/89bff503-7d54-4922-9da3-5a014266b8c3)

**Comment by EvHaus** [comment]
I'm also looking for this support. At the moment, I can hack around it by adding this at the top of the Elysian chain:

```ts
.onError(({ error }) => {
	return Response.json({error: error.message});
})
```

But this doesn't get handled nicely by Eden since it doesn't know that `{error: string}` will now be a valid response type from all API endpoints, so you end up needing to hack around the missing types on the client:

```ts
import { edenTreaty } from '@elysiajs/eden';
import type { App } from 'backend';

const api = edenTreaty<App>('api/');

const {data, error} = api.someendpoint.get();

// Eden doesn't know that `data` will return `{error: string}` when a failure occurs :(
// So we have to add a type assertion
const typedData = data as (typeof data) | {error: string}

if (error) {
    console.log("Failed due to", typedData.error);
}
```

**Comment by EvHaus** [comment]
Ok, I think I have something more-or-less functional in Elysia 1.0.

### Step 1

Create a custom `Error` object as per [the docs](https://elysiajs.com/life-cycle/on-error.html#custom-error). In my case I called it `APIError`. This is needed so you can pass custom values (like status codes) through to Elysia's `onError` function.

Mine looks like this:

```ts
import type { StatusCodes } from 'http-status-codes';

export class APIError extends Error {
  public readonly message: string;
  public readonly httpCode: StatusCodes;

  constructor(httpCode: StatusCodes, message: string, options?: ErrorOptions) {
    super(message, options);

    this.httpCode = httpCode;
    this.message = message;
    this.name = 'APIError';

    Object.setPrototypeOf(this, APIError.prototype);
    Error.captureStackTrace(this);
  }
}
```

### Step 2

In your route handlers, throw these custom errors as needed. Example:

```ts
new Elysia().post('/myendpoint', async () => {
  if (somethingWentWrong) throw new APIError(422, 'Your custom error message here')
});
```

### Step 3

In your global Elysia chain, add an `onError` handler that will intercept errors:

```ts
import type { ParseError, ValidationError } from 'elysia';

const errors = new Elysia()
  .error({ APIError })
  .onError({ as: 'global' }, ({ error, request, set, code }) => {
    logger.error(error);
    captureException(error);

    let message = 'Unknown error';
    set.status = StatusCodes.INTERNAL_SERVER_ERROR;

    switch (code) {
      case 'NOT_FOUND':
        set.status = StatusCodes.NOT_FOUND;
        message = `${request.method} ${request.url} is not a valid endpoint.`;
        break;
      case 'PARSE':
        // I'm not sure why type narrowing isn't working here
        set.status = (error as ParseError).status;
        message = (error as ParseError).message;
        break;
      case 'VALIDATION':
        set.status = (error as ValidationError).status;
        // NOTE: You might want to concat all validation errors here
        message = (error as ValidationError).all[0].schema.error;
        break;
      case 'APIError':
        set.status = (error as APIError).httpCode;
        message = (error as APIError).message;
        break;
    }

    return Response.json(
      { error: message },
      { headers: set.headers, status: set.status },
    );
  });
```

> [!NOTE]
> Do not use `import {error} from 'elysia'`. It seems to bypass the `onError` handler.

### Step 4

Seems to work fine in `treaty` as well, like so:

```ts
import { treaty } from '@elysiajs/eden';
import { app } from './index';

const api = treaty(app);
const { error, status } = await api.myendpoint.post();

console.log(error.value)
// => {error: 'Your custom error message here', otherstuff: 'whatever you want'}
```

### Pitfalls

1. Unfortunately `error` will be typed as `unknown` in this case. It looks like there should be a way to fix this, but my TypeScript skills are not good enough to figure out how. Any help would be appreciated.
2. If you print `error` you get this ugly/useless thing: `Error: [object Object]`. It's not obvious that you have to use `error.value`.

**Comment by algora-pbc** [comment]
💎 **ev** is offering a **$100** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #313` in the PR body and joining algora.io

**Comment by SaltyAom** [comment]
All Elysia built-in errors should have been returning as JSON since ~0.7.0 by default

**Comment by EvHaus** [comment]
I'll try to describe the request and problem more clearly.

Elysia's ["Error Handling" docs](https://elysiajs.com/life-cycle/on-error.html#example) provide this basic example:

```ts
const app = new Elysia()
    .onError(({ code, error }) => {
        return new Response(error.toString())
    })
    .get('/', () => {
        throw new Error('Server is during maintenance')
    })
```

This results in a request to `/` returning a 200 text response "Error: Server is during maintenance".

Let's change this to return a JSON error instead:

```ts
const app = new Elysia()
    .onError(({ code, error }) => {
        // With this change, I'm hoping Elysia will now return {failure: 'Server is during maintenance'}
        return {failure: error.message}
    })
    .get('/', () => {
        throw new Error('Server is during maintenance')
    })
```

Ok great! It works. A request to `/` now returns a 500 error with `{"failure":"Server is during maintenance"}`.

> [!NOTE]
> Interestingly (but unrelated), a `return {failure: error.message}` will set the response status to 500, but `return Response.json({failure: error.message})` will return a status of 200.

Now let's try to use this API from the client-side using Eden (as per [the docs](https://elysiajs.com/eden/treaty/overview.html#eden-treaty)):

```ts
import { treaty } from '@elysiajs/eden'
import type { App } from '../src'

const app = treaty<App>('localhost:3000')
const { data, error } = await app.index.get();

if (error) { 
    // The desire is that `error` would have the type: `{failure: string}`
    console.log(error);
}
```

However, instead, the type is derived as:

```ts
{
  status: unknown;
  value: unknown;
} | null
```

You can also see this on the Elysia docs website itself too:

![image](https://github.com/user-attachments/assets/3475cc14-e23d-4bba-8a50-613afba05e2b)

Instead, I'm expecting `error` to have the type:

```ts
{
  failure: string
}
```

**Comment by DaniumX** [comment]
Any update on this? I really don't like having status and value being of type unknown when their structure is known. Any one know of a way to cast the error in each request? Can it somehow be casted globally when instantiating the Eden client?

**Comment by godlymane** [comment]
/attempt #313

I found a narrower path that matches the clarified Eden typing request: plain values returned from onError currently get recorded in route metadata as 200 responses even though runtime preserves the error status, e.g. an unhandled Error returns the custom JSON body with HTTP 500. I’m adding a focused type-level fix so Eden can see the custom error body under an error status, while keeping explicit status(404, ...) responses unchanged.

**Comment by thefuturrjfhejh** [comment]
/attempt #313

I reproduced the Eden-facing type issue in `test/types/index.ts`: a plain object returned from `onError` is currently recorded as a `200` response even though runtime keeps the thrown error status. I’m taking the narrow type-level path: keep explicit `status(...)` returns as-is, map plain `onError` returns onto the default error status, and cover it in the existing type suite.

**Comment by shaiananvari8** [comment]
/attempt #313

I am taking the narrow type-level path described in the issue: plain objects returned from `onError` currently get inferred as a 200 response even though runtime preserves the error status, commonly 500 for thrown errors. I will add a focused error-handler response schema helper so explicit `status(...)` returns keep their explicit status while plain `onError` returns are recorded under the default error status, with a type test covering the Eden-facing custom JSON error body.

**Comment by half-programmer** [comment]
/attempt #313

Plan: add an error-handler-specific response-schema helper so plain objects returned from `onError` are also exposed under an error status for Eden/client typing, while preserving explicit `status(...)` responses. I will include focused type coverage for custom JSON error responses and existing lifecycle soundness.

**Comment by namdamdoi68-oss** [comment]
Hi @SaltyAom, just a heads-up: I have already resolved this issue with PR #1932 (which was opened 11 days ago, has 100% green tests, and is fully ready for merge). The recent PR #1942 opened by @half-programmer is a direct copy of my work from PR #1932 (same types, patches, and test code). Please review my original PR #1932 when you have a moment. Thank you!

**Comment by ykbhm500-cyber** [comment]
/attempt #313

Plan: inspect the relevant source and tests, make the smallest focused change, independently review the diff, then verify before submitting.

**Comment by zacharywomack8-source** [comment]
Implemented the typing side of this: a plain return from `onError` now types the response as the error statuses (400/404/422/500) instead of 200, while `status()`/`error()` still keep their exact code. See PR https://github.com/elysiajs/elysia/pull/1966.

**Comment by Kesav2k04** [comment]
@EvHaus status question on the bounty rather than an attempt claim.

There are 11 open PRs on this issue right now and none has been reviewed. Before anyone spends more time here, could you confirm whether the $100 is still active?

I ask because Algora keeps rendering withdrawn bounties at full price. On `drizzle-team/drizzle-orm#1188` and `rc0/mairix#29` the funders cancelled in an ordinary comment and both listings still show their original figure, so the board is not a reliable signal either way.

If it is still live, I would want @SaltyAom's read on the intended behaviour before writing any code, since your 2024-07-24 clarification and his 2024-07-23 reply point at different scopes and the open PRs are each guessing at it.

**Comment by SaltyAom** [comment]
@Kesav2k04 You can override the error like this:
```ts
new Elysia()
	.onError(({ code, error }) => {
		if (error instanceof Error) return { ...error, message: error.message }
		if (typeof error === 'string') return { message: error }

		return { ...error }
	})
	.get('/', () => {
		throw new Error('Hello World')
	})
	.listen(3001)
```

Which should make all errors return as JSON.

But it doesn't cover type safety, which is fixed in Elysia 2.

And in Elysia 2, the default Elysia error follows RFC9457, which is JSON.

**Comment by EvHaus** [comment]
> But it doesn't cover type safety, which is fixed in Elysia 2.

@SaltyAom Thanks for the hard work here! I've been testing Elysia 2.0.0-beta.14, and it addresses the runtime half of this (built-in JSON errors). It still doesn't address Eden typing a custom JSON error body for `throw` or a global `.error()` or `.onError()`, especially once routes live on child new `Elysia()` instances composed with `.use()`.

Here are the examples using the basic snippet I posted earlier.

## What I want (same as before)

```ts
import { Elysia } from 'elysia'
import { treaty } from '@elysia/eden'

const app = new Elysia()
	.error(({ error }) => {
		return { failure: error instanceof Error ? error.message : String(error) }
	})
	.get('/', () => {
		throw new Error('Server is during maintenance')
	})

export type App = typeof app

const client = treaty<App>('localhost')
const { error } = await client.index.get()

if (error) {
	// Ideally: `error.status` is `500` here and `error.value` is `{ failure: string }`
	console.log(error.value.failure)
}
```

Runtime is fine in 2.0. The HTTP server returns 500 with `{"failure":"Server is during maintenance"}`.

Eden is still not. `error` is still effectively `{ status: unknown; value: unknown } | null`. It is not `{ failure: string }`.

The [2.0 blog](https://elysiajs.com/blog/elysia-20#_1-redundant-boilerplate) shows how to type this, but only with a different program:

```ts
class MyError extends Error {}
const errorBoundary = new Elysia({ name: 'boundary', as: 'global' }).error(
	MyError,
	({ status, error }) => status(418, error.message),
)

const app = new Elysia()
	.use(errorBoundary)
	.get('/', () => new MyError('A')) // return, same instance

type Response = typeof app['~Routes']['get']['response']
// { 418: string }  — this works
```

That is a different contract than what I would expect from global error mapper though.

## What approaches still fail when I've tried them

### 1. throw is invisible to the route type

```ts
.get('/', () => {
	throw new MyError('A') // runtime 418, Eden does not see 418
})
```

TypeScript does not put `throw` in the return type, so `.error(MyError, …)` never gets applied to `~Routes`.

### 2. Child instances do not inherit the parent error map despite being global

```ts
const errorBoundary = new Elysia({ as: 'global' }).error(
	MyError,
	({ status, error }) => status(418, { failure: error.message }),
)

const child = new Elysia().get('/child', () => {
	throw new MyError('A')
	// or even: return new MyError('A')
})

const app = new Elysia().use(errorBoundary).use(child)

type ChildResponse = typeof app['~Routes']['child']['get']['response']
// no 418 / no { failure: string } on Eden error.value
```

We split routes across many `new Elysia()` trees and compose them to stay under the TS instantiation limit (still needed in 2.0).

3. `HTTPError` / `problem()` with a dynamic `status: number` also does not produce a status map

```ts
class APIError extends HTTPError {
	override readonly status: number
	constructor(status: number, message: string) {
		super(message)
		this.status = status
	}
}
.get('/item', () => {
	throw new APIError(422, 'Your custom error message here')
})
```

Eden still does not give `error.value` a usable body type. We only get types if we return `problem(422, { detail }) / status(418, …)` with a literal status from that handler.

### Workaround we had to add (and do not want)

A `guard({ response: { 400: schema, 401: schema, … } })` on every declaring instance so treaty sees `error.value.detail`. That is the 1.x response-map boilerplate 2.0 was hoping to remove.

Happy to put this in a minimal repro repo if useful. My wish list is still the same from earlier: if I map errors to JSON once in a global handler, Eden should type `error.value` as that JSON (and `error.status` as the HTTP status), including for throw and for routes registered on child instances.

**Comment by devamkakoty** [comment]
@EvHaus @SaltyAom — AI-assisted inquiry on behalf of Devam Kakoty; no claim or implementation started.

The September 14 reproduction appears to identify a more specific gap than the earlier runtime JSON issue: propagating an explicitly registered global error mapper into the response types of child routes composed with `.use()`. Inferring arbitrary thrown classes from a TypeScript return type is a separate limitation, so I would not promise to solve that with hard-coded built-in status unions.

Is the advertised **$100 reward still active**, and would a regression for the global-mapper/child-route case plus a narrowly scoped fix be useful? Please also confirm the intended target branch/version and whether that slice would qualify, rather than assuming it resolves the entire wish list.

I have read the contribution requirement for human interaction, review and supervision of AI-assisted PRs. Any submission would need that requirement met; I am not claiming human review has already happened. If this is already covered by an existing PR or is not a wanted separate contribution, I will not duplicate it.

**Comment by SaltyAom** [comment]
@EvHaus Hi, let me clarify

1. It's simply not possible to make TypeScript infer a type from `throw`. TypeScript just doesn't support that at all.
2. Similar to 1. Not possible to infer type from catch similar. If you return, it should map. We take care of that.
3. Simiar to 1 as well. But if you use return, you must make the status statically analyable using generic

```ts
class APIError<
	T extends number,
	const Message extends string
> extends HTTPError.id('API_ERROR') {
	constructor(
		public status: T,
		public message: Message
	) {
		super(message)
		this.status = status
	}

	value() {
		return this.message
	}
}

const app = new Elysia().get('/item', () => {
	if (Math.random() > 0.5)
		return new APIError(418, 'I maybe a Teapot')

	return new APIError(422, 'I maybe a validation error')
})

// 418 and 422
type Response = (typeof app)['~Routes']['item']['get']['response']
```

Alternatively, if you want an APIError to have a fixed status code, it would be much easier:
```ts
class APIError extends HTTPError.id('API_ERROR', 422) {
	constructor() {
		super("Thing just got out of hand")
	}
}

const app = new Elysia().get('/item', () => {
	return new APIError()
})

// 422
type Response = (typeof app)['~Routes']['item']['get']['response']
```

**Comment by devamkakoty** [comment]
AI-assisted follow-up on my earlier scope inquiry; this is a local check, not a fix or bounty claim.

I checked the narrow **returned `MyError` + anonymous global error boundary + separately constructed child `.use()`** case with `elysia@2.0.0-beta.14` and TypeScript `5.9.2`. Both the same-chain control and the separately composed child retain `{ 418: { readonly failure: string } }`. The thrown-error control has no inferred `418`, consistent with the limitation explained above.

The first exact-equality assertion incorrectly expected a mutable `failure` property. Inspecting the inferred types exposed that test mistake; the corrected anonymous-boundary reproduction passes its three assertions. This was a compile-only consumer check with `skipLibCheck: true`, not a clean upstream build, runtime test, or Eden-client test.

So I am **not pursuing a fix or reward for that returned-child slice as reproduced**. This does not establish that every case in the original request is resolved. A materially different failing reproduction would need to identify the remaining gap before further work. No PR or bounty claim has been submitted.

**Comment by SaltyAom** [comment]
Closing this as solved by [Elysia 2.0](https://elysiajs.com/blog/elysia-20) to prevent `/attempt #313` spam.

Elysia 2 now returns the default Elysia error as an RFC 9457 by default

Unknown error can now also be overridden with full type-safety support for Eden as well
<img width="2096" height="1662" alt="Image" src="https://github.com/user-attachments/assets/c1774db4-976d-401e-98ae-bd51083c5ef8" />

> [@EvHaus](https://github.com/EvHaus) Hi, let me clarify
> 
> 1. It's simply not possible to make TypeScript infer a type from `throw`. TypeScript just doesn't support that at all.
> 2. Similar to 1. Not possible to infer type from catch similar. If you return, it should map. We take care of that.
> 3. Simiar to 1 as well. But if you use return, you must make the status statically analyable using generic
> 
> class APIError<
> 	T extends number,
> 	const Message extends string
> > extends HTTPError.id('API_ERROR') {
> 	constructor(
> 		public status: T,
> 		public message: Message
> 	) {
> 		super(message)
> 		this.status = status
> 	}
> 
> 	value() {
> 		return this.message
> 	}
> }
> 
> const app = new Elysia().get('/item', () => {
> 	if (Math.random() > 0.5)
> 		return new APIError(418, 'I maybe a Teapot')
> 
> 	return new APIError(422, 'I maybe a validation error')
> })
> 
> // 418 and 422
> type Response = (typeof app)['~Routes']['item']['get']['response']
> Alternatively, if you want an APIError to have a fixed status code, it would be much easier:
> 
> class APIError extends HTTPError.id('API_ERROR', 422) {
> 	constructor() {
> 		super("Thing just got out of hand")
> 	}
> }
> 
> const app = new Elysia().get('/item', () => {
> 	return new APIError()
> })
> 
> // 422
> type Response = (typeof app)['~Routes']['item']['get']['response']
