### ISSUE TITLE
no catch case in case DELETE request has no body

### ISSUE THREAD

**Issue by huilensolis** [elysiajs/elysia#495]
### What version of Elysia.JS is running?

0.8.17

### What platform is your computer?

Linux 6.5.5-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

- [ ] Set up an Elysia JS server
- [ ] Set up a .onError method on your elysia app
```ts
YourElysiaApp.onError(({ code, error, path, set }) => {
  console.log({ path, error, code });
})
```
- [ ] Set up a route with a DELETE method
- [ ] Create a request with the fetch API on bun with DELETE method and headers content type application/json
```ts
    const res = await app.handle(
      new Request(`${endpointPath}/`, {
        method: "DELETE",
        headers: { "Content-Type": "application/json" }
      }),
    );
```
- [ ] check the console

### What is the expected behavior?

don't throw an error if the request has no body, or provide a descriptive error message letting the developer know that the error is being thrown because he has setten 'Content-type': 'aplication/json' but there was an error parsing the body.
or explain that the request body is going to be parsed always.

### What do you see instead?

```bash
{
  path: "/user/",
  error: 61 |                                   const index = contentType.indexOf(';')
62 |                                    if (index !== -1) contentType = contentType.substring(0, index)
63 |
64 |                            switch (contentType) {
65 |                                    case 'application/json':
66 |                                            c.body = await c.request.json()
                          ^
SyntaxError: Unexpected end of JSON input
,
  code: "UNKNOWN",
}
```

**Comment by SaltyAom** [comment]
Fixed in [711925a](https://github.com/elysiajs/elysia/pull/465/commits/711925a5b5561452b58979b26917cb13a6cf8d9c) under `1.0.0-beta.14`.

If resolved, please leave the issue opened until release on next stable release.

**Comment by msanchezdev** [comment]
@SaltyAom when the body is extracted or accessed the following error is thrown:
```
Error: Failed to parse body as found: ''
```

It no longer erros with unexpected end of json input but still throwing when trying to parse the body on an onBeforeHandle or onTransform, haven't tried other cases. Been trying to make a log for all requests:

```typescript
  .onRequest(async ({ request }) => {
    console.log('< req.url =', request.url);
    console.log('< req.method =', request.method);
    console.log('< req.headers =', request.headers);
  })
  .onBeforeHandle(async ({ body }) => {
    console.log('< req.body =', body);
    console.log();
  })
  .onResponse(async ({ set }) => {
    console.log('> status =', set.status);
    console.log();
  })
```

I think we should have a default value for the body if possible (when type is explicitly set?), in cases where the body hasn't been parsed or cant be known (`onTransform` or `onBeforeHandle` which are my case)

PD: Out of the scope of this ticket but would be great to have access to the response body on an `onResponse` or `onAfterHandle`

**Comment by kravetsone** [comment]
> ### What version of Elysia.JS is running?
> 0.8.17
> 
> ### What platform is your computer?
> Linux 6.5.5-arch1-1 x86_64 unknown
> 
> ### What steps can reproduce the bug?
> * [ ]  Set up an Elysia JS server
> * [ ]  Set up a .onError method on your elysia app
> 
> ```ts
> YourElysiaApp.onError(({ code, error, path, set }) => {
>   console.log({ path, error, code });
> })
> ```
> 
> * [ ]  Set up a route with a DELETE method
> * [ ]  Create a request with the fetch API on bun with DELETE method and headers content type application/json
> 
> ```ts
>     const res = await app.handle(
>       new Request(`${endpointPath}/`, {
>         method: "DELETE",
>         headers: { "Content-Type": "application/json" }
>       }),
>     );
> ```
> 
> * [ ]  check the console
> 
> ### What is the expected behavior?
> don't throw an error if the request has no body, or provide a descriptive error message letting the developer know that the error is being thrown because he has setten 'Content-type': 'aplication/json' but there was an error parsing the body. or explain that the request body is going to be parsed always.
> 
> ### What do you see instead?
> ```shell
> {
>   path: "/user/",
>   error: 61 |                                   const index = contentType.indexOf(';')
> 62 |                                    if (index !== -1) contentType = contentType.substring(0, index)
> 63 |
> 64 |                            switch (contentType) {
> 65 |                                    case 'application/json':
> 66 |                                            c.body = await c.request.json()
>                           ^
> SyntaxError: Unexpected end of JSON input
> ,
>   code: "UNKNOWN",
> }
> ```
> 
> ### Additional information
> _No response_

Why would you lie to the server about the content-type?

**Comment by assapir** [comment]
Not sure if it is related or not, but when I am trying to send a `DELETE` request without body, I am getting the following error:
```
Failed to parse body as found: undefined
```

the handler itself is defined as:
```ts
.delete('/:id', async ({ safeSession }) => {
  await deleteSafeSession(safeSession!.id);
  return {
  sessionId: safeSession!.id,
  };
});
```

with the following before:
```ts
.derive(async ({ params: { id } }) => {
  const safeSession = await getSafeSessionById(id);
  return {
    safeSession,
  };
})
.onBeforeHandle(({ safeSession, set, accountId }) => {
  if (!safeSession || safeSession.store.accountId !== accountId) {
    return sendUnauthorizedResponse(set);
  }
})
```

**Comment by SaltyAom** [comment]
Fixed with 1678c63.

Feel free to reopen the issue if the problem still persists.
