### ISSUE TITLE
Transform type (include Date) won't transform in Array schema

### ISSUE THREAD

**Issue by drsmile1001** [elysiajs/elysia#671]
### What version of Elysia.JS is running?

1.0.22

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

##### Date schema
bun run code below:
```typescript
await new Elysia()
  .post("/inArrayOfObject", ({ body }) => body[0].time.getFullYear(), {
    body: t.Array(
      t.Object({
        time: t.Date(),
      })
    ),
  })
  .handle(
    new Request("http://localhost/inArrayOfObject", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: `[{"time":"2024-06-06T00:00:00.000Z"}]`,
    })
  )
  .then((res) => res.text())
  .then(console.log);
```
will throw

> {"name":"TypeError","message":"body[0].time.getFullYear is not a function. (In 'body[0].time.getFullYear()', 'body[0].time.getFullYear' is undefined)"}

log body will get:
```
[
  {
    time: "2024-06-06T00:00:00.000Z",
  }
]
```

shows time doesn't transform to Date.

#### Custom Transform
bun run code below:
```typescript
import { Elysia, t } from "elysia";

await new Elysia()
  .post("/customTransformInArrayOfObject", ({ body }) => body, {
    body: t.Array(
      t.Object({
        v: t
          .Transform(t.String())
          .Decode((value) => parseFloat(value))
          .Encode((value) => value.toString()),
      })
    ),
  })
  .handle(
    new Request("http://localhost/customTransformInArrayOfObject", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: `[{"v":"3.14"}]`,
    })
  )
  .then((res) => res.text())
  .then(console.log);
```
will got
`[{"v":"3.14"}]`

shows string doesn't transform to number.

### What is the expected behavior?

While `Transform schema` do not nest in array. It transform correctly.

```typescript
import { Elysia, t } from "elysia";

await new Elysia()
  .post("/inObject", ({ body }) => body, {
    body: t.Object({
      v: t
        .Transform(t.String())
        .Decode((value) => parseFloat(value))
        .Encode((value) => value.toString()),
    }),
  })
  .handle(
    new Request("http://localhost/inObject", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: `{"v":"3.14"}`,
    })
  )
  .then((res) => res.text())
  .then(console.log); //got `{"v":3.14}`
```

```typescript
import { Elysia, t } from "elysia";

await new Elysia()
  .post("/inObject", ({ body }) => body.time.getFullYear(), { //transform success
    body: t.Object({
      time: t.Date(),
    }),
  })
  .handle(
    new Request("http://localhost/inObject", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: `{"time":"2024-06-06T00:00:00.000Z"}`,
    })
  )
  .then((res) => res.text())
  .then(console.log); // got 2024
```

```typescript
await new Elysia()
  .post("/inArrayOfObject", ({ body }) => body[0].time.getFullYear(), {
    body: t.Array(
      t.Object({
        time: t.Date(),
      })
    ),
  })
  .handle(
    new Request("http://localhost/inArrayOfObject", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: `[{"time":"2024-06-06T00:00:00.000Z"}]`,
    })
  )
  .then((res) => res.text())
  .then(console.log); //got 2024
```

So, `Transform schema` should transform nest in array. Like below:

```typescript
import { Elysia, t } from "elysia";

await new Elysia()
  .post("/customTransformInArrayOfObject", ({ body }) => body, {
    body: t.Array(
      t.Object({
        v: t
          .Transform(t.String())
          .Decode((value) => parseFloat(value))
          .Encode((value) => value.toString()),
      })
    ),
  })
  .handle(
    new Request("http://localhost/customTransformInArrayOfObject", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: `[{"v":"3.14"}]`,
    })
  )
  .then((res) => res.text())
  .then(console.log); //got 3.14
```

**Comment by awilderink** [comment]
I got a similar problem when I use `t.Array(t.Numeric())` it works fine when I use `Value.Decode` but that means I'll have to decode it manually every time which is not ideal.

**Comment by zoriya** [comment]
It seems to work better but it triggered a regression. The following snippet doesn't work:

```typescript
import { Elysia, t } from "elysia";

new Elysia()
	.get(
		"/test",
		({ query: { id } }) => ({
			id,
			type: typeof id,
		}),
		{
			query: t.Object({
				id: t
					.Transform(t.Array(t.UnionEnum(["test", "foo"])))
					.Decode((id) => ({ value: id }))
					.Encode((id) => id.value),
			}),
		},
	)
	.listen(3000);
```

`$ curl 'localhost:3000/test?id=test' | jq`
```json
{
  "message": "Validation error on property.",
  "details": {
    "type": "validation",
    "on": "property",
    "summary": "Expected array",
    "property": "root",
    "message": "Expected array",
    "expected": [],
    "found": {
      "value": [
        "test"
      ]
    },
    "errors": [
      {
        "summary": "Expected array",
        "type": 6,
        "schema": {
          "type": "array",
          "items": {
            "default": "test",
            "type": "string",
            "enum": [
              "test",
              "foo"
            ]
          }
        },
        "path": "",
        "value": {
          "value": [
            "test"
          ]
        },
        "message": "Expected array",
        "errors": []
      }
    ]
  }
}

```

**Comment by SaltyAom** [comment]
@zoriya should have been fixed with [86ec566](https://github.com/elysiajs/elysia/commit/86ec5667d92b30b91e6ff71e7b0e2b6e2026e892), published under 1.2.20

**Comment by zoriya** [comment]
It indeed fixed the Array/Transform issue, but the issue still occurs with some types (`Intersect` for example). Here's a minimal example:

```typescript
new Elysia()
	.post("/test", ({ body }) => body, {
		body: t.Intersect([
			t.Object({ foo: t.String() }),
			t.Object({
				field: t
					.Transform(t.String())
					.Decode((x) => ({ decoded: x }))
					.Encode((x) => x.decoded),
			}),
		]),
	})
	.listen(3000);
```

with `$ curl -X post 'localhost:3000/test' -d '{"field": "bar", "foo": "test"}' -H "content-type: application/json" | jq`
expected:
```json
{
  "foo": "test",
  "field": {
    "decoded": "bar"
  }
}
```
got:
```json
{
  "foo": "test",
  "field": "bar"
}
```

**Comment by SaltyAom** [comment]
@zoriya fixed by [3fb45d6](https://github.com/elysiajs/elysia/commit/3fb45d6599dd90ddc2146a86c126a7e719481d13) published under 1.2.21

**Comment by zoriya** [comment]
I confirm the fix works! thanks!

**Comment by drsmile1001** [comment]
I think it fixed. Thanks @SaltyAom !
