### ISSUE TITLE
Building elysia v1.2.2 via `next build` crashes with "Can't resolve 'fs'"

### ISSUE THREAD

**Issue by EvHaus** [elysiajs/elysia#971]
### What version of Elysia is running?

1.2.2

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

In a Next.js project add a file that uses Typebox from Elysia:

```ts
import { t } from 'elysia';

export const sampleSchema = t.Object({})
```

Then build the project with `next build`.

### What is the expected behavior?

The build should succeed.

### What do you see instead?

The build fails with:

```
Failed to compile.

../../node_modules/.pnpm/elysia@1.2.2_@sinclair+typebox@0.34.13_typescript@5.7.2/node_modules/elysia/dist/universal/fs.mjs:2:1
Module not found: Can't resolve 'fs'
Did you mean './fs'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /myproject/node_modules/.pnpm/next@15.1.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/bin/node_modules, /myproject/node_modules/.pnpm/next@15.1.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/node_modules, /myproject/node_modules/.pnpm/next@15.1.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/node_modules, /myproject/node_modules/.pnpm/next@15.1.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules, /myproject/node_modules/.pnpm/node_modules, /myproject/packages/forge-web).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
  1 | import{ env }from"./env.mjs";
> 2 | const fs = typeof process !== "undefined" && env.NODE_ENV ? await import("fs") : {};
    | ^
  3 | const noop = () => {
  4 | };
  5 | const createReadStream = fs.createReadStream ?? noop;

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/.pnpm/elysia@1.2.2_@sinclair+typebox@0.34.13_typescript@5.7.2/node_modules/elysia/dist/universal/file.mjs
../../node_modules/.pnpm/elysia@1.2.2_@sinclair+typebox@0.34.13_typescript@5.7.2/node_modules/elysia/dist/index.mjs
../rs-api/models/organization.ts
./pages/onboarding/index.tsx


> Build failed because of webpack errors
 ELIFECYCLE  Command failed with exit code 1.
```

 
<img width="1418" alt="Screenshot 2024-12-23 at 10 21 50 PM" src="https://github.com/user-attachments/assets/29d19add-7c86-4415-8442-d59d467456e2" />

### Additional information

Rolling back to 1.1.27 fixes the problem.

### Have you try removing the `node_modules` and `bun.lockb` and try again yet?

Yes

**Comment by 0-don** [comment]
having the same issue using as nextjs adapter only with nodejs

**Comment by SaltyAom** [comment]
Fixed in https://github.com/elysiajs/elysia/commit/e83daaf23937c94c048ec00f5024f45890df9864, published under 1.2.3

**Comment by 0-don** [comment]
@SaltyAom  
![image](https://github.com/user-attachments/assets/3d4a3df1-27a5-403a-9bdc-e34bf8e79b82)


its still happening

**Comment by 0-don** [comment]
here is an example project https://github.com/0-don/coding.global-web

**Comment by EvHaus** [comment]
I'm also still have a related, but slightly different issue on 1.2.9. The app now fails to build with:

```
./node_modules/.pnpm/elysia@1.2.9_@sinclair+typebox@0.34.13_typescript@5.7.2/node_modules/elysia/dist/universal/file.mjs:96:24
Module not found: Can't resolve 'fs'
  94 |       } else {
  95 |         if (!createReadStream || !stat) {
> 96 |           this.value = import("fs").then((fs) => {
     |                        ^^^^^^^^^^^^
  97 |             createReadStream = fs.createReadStream;
  98 |             return fs.createReadStream(path);
  99 |           });
```

**Comment by SaltyAom** [comment]
Not sure if this would fix the problem since I couldn't replicate it on my end, but with b1bf2f2 which should be published under 1.2.13 might fixed the problem

**Comment by EvHaus** [comment]
Unfortunately not fixed in 1.2.13:

```
../../node_modules/.pnpm/elysia@1.2.13_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal/file.mjs:96:1
Module not found: Can't resolve 'fs'
  94 |       } else {
  95 |         if (!createReadStream || !stat) {
> 96 |           this.value = import("fs").then((fs) => {
     | ^
  97 |             createReadStream = fs.createReadStream;
  98 |             return fs.createReadStream(path);
  99 |           });
```

However, I'm going to mark this as resolved. If you need Typebox in a Next.js build, you can switch to direct typebox imports instead:

```
// Change this
import {t} from 'elysia';

// to
import {Type} from '@sinclair/typebox'
```

**Comment by kravetsone** [comment]
> Unfortunately not fixed in 1.2.13:
> 
> ```
> ../../node_modules/.pnpm/elysia@1.2.13_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal/file.mjs:96:1
> Module not found: Can't resolve 'fs'
>   94 |       } else {
>   95 |         if (!createReadStream || !stat) {
> > 96 |           this.value = import("fs").then((fs) => {
>      | ^
>   97 |             createReadStream = fs.createReadStream;
>   98 |             return fs.createReadStream(path);
>   99 |           });
> ```
> 
> However, I'm going to mark this as resolved. If you need Typebox in a Next.js build, you can switch to direct typebox imports instead:
> 
> ```
> // Change this
> import {t} from 'elysia';
> 
> // to
> import {Type} from '@sinclair/typebox'
> ```

or `import { t } from "elysia/type-system";`

**Comment by SaltyAom** [comment]
I forgot to warp another `import('fs')` in 1.2.13, can you check if it works on 1.2.14? thanks

**Comment by kravetsone** [comment]
> I forgot to warp another `import('fs')` in 1.2.13, can you check if it works on 1.2.14? thanks

Maybe we can add test with Bun.build target web?

**Comment by EvHaus** [comment]
> I forgot to warp another import('fs') in 1.2.13, can you check if it works on 1.2.14? thanks

The build script completed this time! But with warnings:

```
⚠ Compiled with warnings

../../node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal/file.mjs
Module not found: Can't resolve 'fs' in '/Users/me/proj/node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal'

Import trace for requested module:
../../node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal/file.mjs
../../node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/index.mjs
./components/AppLayout/AppLayout.tsx

../../node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal/file.mjs
Module not found: Can't resolve 'fs/promises' in '/Users/me/proj/node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal'

Import trace for requested module:
../../node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/universal/file.mjs
../../node_modules/.pnpm/elysia@1.2.14_@sinclair+typebox@0.34.25_typescript@5.7.3/node_modules/elysia/dist/index.mjs
./components/AppLayout/AppLayout.tsx
```
